### ISSUE TITLE
$config array instead of multiple $config['settings'] lines

### ISSUE THREAD

**Issue by theshka** [smcdougall/NotePaper#1]
Since the theme has so many configuration options, it's probably best to organize it into a `$config['NotePaper'] = array();` instead of placing multiple (possibly conflicting) different `$config['setting'] = val;` lines in the `config/config.php`

Something like... 

``` php
$config['NotePaper'] = array(
    #Basic Config
    'site_logo'         => '/content/site_logo.png',
    'css_override'      => null, # e.g. '/content/css-override.css',
    'og_image'          => 'assets/site_logo_og.png',
    'ToC'               => 'Table of Contents',
    'copyright'         => 'Copyright © 20XX - Your Name',
    #Front Page Mode
    'front_page_mode'   => array(
        'enabled'           => '',
        'front_page_limit'  => 5
    ),
    #Disqus Config 
    'disqus' => array(
        'enabled'   => 'yes',
        'shortname' => 'your-shortname-here'
    ),
    #Bottom Links Config
    'bottom_links' => array(
        'enabled'           => 'yes',
        'first_text'        => '<< First',
        'first_image'       => 'assets/button_first.png',
        'prev_text'         => '< Prev',
        'prev_image'        => 'assets/button_prev.png',
        'next_text'         => 'Next >',
        'next_image'        => 'assets/button_next.png',
        'last_text'         => 'Last >>',
        'last_image'        => 'assets/button_last.png',
        'top_text'          => 'Back to Top',
        'top_image'         => 'assets/button_top.png',
        'separator'         => '|',
        'separator_image'   => 'assets/button_separator.png'
    )
);
```

In your `.twig`/`.html` file, you could access them by `config.NotePaper.disqus.shortname`, etc.. 
in PHP  $config['NotePaper']['disqus']['shortname'] = '';`

Thoughts?

**Comment by mayamcdougall** [comment]
I thought about that!  I couldn't figure out how to do it.  I don't know what I was thinking that day because I tried to define it as a twig array instead of a php one. :sweat: I didn't break it out into new lines though (it was only the first few `bottom_links` items), and I just thought that it _looked_ too intimidating for a user to configure, so I dropped the idea.

Actually seeing it fully formatted though, it looks pretty good.  I'll definitely switch it to an array.  Thanks!

Also, Is there any difference to specifying `null` vs just leaving empty quotes?

**Comment by theshka** [comment]
Yes and no, I guess it just depends how you check it with php `isset`/`is_null` and `empty`. I stuck a `null` there while I was transferring it over to an array because I thought it would override in the theme (and that isn't the path to the themes css file) 

I'm glad you like the idea :smile:

**Comment by mayamcdougall** [comment]
Actually, the css_override is a second stylesheet linked (in the html) after the first.  If it doesn't exist, it just 404's and there's no real harm. :smile: The default styles are _always_ loaded first, then the override file just contains the items you wish to change.  I did it to provide a quick way to change the background or color scheme.  For example, I'll probably include [this override](http://writing.sjmcdougall.com/) as an alternate style in the future.

Right now, I'm checking for the override using `{% if config.css_override %}`, which returns false with either blank quotes or null.  If it is defined but has a bad url, the theme doesn't break, it just uses the default styles.  I'll probably continue use blank quotes, as it provides a nice indication to the user of where they should put their info (and prevents them from forgetting the quotes altogether).

Do you think I should provide the config setup in an example file, like `sample-config.php` or would this be too confusing?  Right now the [example site](http://development.sjmcdougall.com/pico-themes/NotePaper/) and the `readme.md` (which _generates_ the example site) are the only places to find this information.  As it stands, it's getting a little unreadable with all the config variables squashed into a small area.  I'm thinking I may make that section collapse or break it into another page.

**Comment by mayamcdougall** [comment]
Done! https://github.com/smcdougall/NotePaper/commit/9fa270408a0e3c8f9b26fa6050e014fd2027b20d

Thanks for the tip! :smile: :+1:
