### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by MrReichert** [smcdougall/NotePaper#13]
I tried to install this, at first I get error saying no style.css file found, so I found it in the zip file. I moved it to the root folder and zipped it up and tried to install again. then I get error saying, The style.css stylesheet does not contain a valid theme header.

Theme installation failed.

I am trying to install this to a free site called X10 Hosting site, wordpress is up and running, just can't get this theme to work. 

any help would be appreciated.

**Comment by mayamcdougall** [comment]
Sorry, but this isn't a Wordpress theme.  It's a theme for [PicoCMS](https://picocms.org/) (and was once, very long ago, *inspired* by a Wordpress theme, which no longer exists).
