### ISSUE TITLE
Directory Structure for GitHub

### ISSUE THREAD

**Issue by mayamcdougall** [smcdougall/NotePaper#2]
So, originally I put my LICENSE and readme files inside the theme folder, that way they'd always be included in an installation of my theme, in case someone was looking for them (mostly for the sake of the readme though, not the license).

On GitHub however, this contradicts the usual layout of a project, where the license and readme files are at the root of the project.  For the time being, I just symlinked them from the theme folder, but this isn't a great solution.

I'm thinking that for the next version, I'll move the license to the project root because if anyone is _really_ looking for that they'll probably come to GitHub anyway.  The readme I'm not sure though.

I don't really want to maintain _two_ copies of the readme, but at the moment I think I'd need one copy for the [website](http://development.sjmcdougall.com/pico-themes/NotePaper/) and one copy that's modified for GitHub (to remove the toc at least because it's ugly on the front page).

I may just remove the copy from the theme folder though, since it'll already be provided online in two places _and_ in the root of the release zip.  There's also a little (removable) link at the bottom of the theme the user could follow if they _really_ forgot where it came from.

(Note to self, I could always add another link at the bottom of the theme (and in the readme) about contributing on GitHub.  Not really looking for code, but issues and suggestions would always be welcome.)

@theshka Sorry for the long post, but could I get your input on it?  It can be ten words or less, you don't need to write your life's story like I apparently do. :wink:

**Comment by theshka** [comment]
I would have all `README`, `LICENSE`, `CONTRIBUTING`, and `CHANGELOG` files in the root of the project @smcdougall, then where to place your other files in relation to where they appear in Pico .. You could link to the readme/license files in comments within your files too.

**Comment by mayamcdougall** [comment]
Done.  My only concern is that if someone just extracts the entire archive directly into their Pico folder, they'll be wiping out Pico's `README` and `LICENSE`.  Since different components are optional though (`content/sample-widgets` for example), I've just change the directions to _Selectively_ extract the files, with the `themes` folder being the only _required_ item.
